### ISSUE TITLE
Recent Valheim Patch Issue

### ISSUE THREAD

**Issue by ValhallaCommunity** [LTmadness/GumshoeTimerSuite#1]
Hi LT!

I think with the recent Valheim Patch 0.216.9, it's possible that there is an update needed with GumshoeTimerSuite!

`[Error  : Unity Log] ArgumentException: Undefined target method for patch method static void GumshoeTimerSuite.GumshoeTimerSuite::UpdateHoverText(Smelter __instance)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.CreateAndPatchAll (System.Type type, System.String harmonyInstanceId) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
GumshoeTimerSuite.GumshoeTimerSuite.Awake () (at <4660d2a915cd4126a4b6a4e5871134f9>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.UI.Image:OnCanvasHierarchyChanged()`

Let me know if you need additional details!

**Comment by LTmadness** [comment]
hey, thanks, have already wrote the update just not finished validating few small bits, will release update today
